### ISSUE TITLE
Clarification on aggregate propagation

### ISSUE THREAD

**Issue by pdeibert** [potassco/mu-gringo#1]
Hello,

thank you for providing us with this project to better understand grounding in ASP.

I am trying to understand the aggregate propagation mechanism, but am not sure that I understand the purpose of `propagate_disjunction` and `propagate_inequal`. 

I am under the assumption that $I\subseteq J$ for the set of certain literals $I$ and set of possible literals $J$. 

For example, in the case of `#count`, the function is strictly increasing with additional elements between the two sets.
If we propagate for the inequality relation, and the lower  (`<`) and upper (`>`) checks are both `false`, then $l>=b$ and $u<=b$ for lower-, upper bounds $l,u$ and guard term $b$. Shouldn't that already mean that $u=l=b$ and also $I=J$? In particular, the set of elements which are not satisfied by $I$, but satisfied by $J$ should be empty, since every additionally satisfied element in $J$ would inevitably result in a different aggregate count for the set of certain and possible literals. That would render `propagate_disjunction` unsatisfiable in my understanding, if propagation for `>` and `<` both already resulted in `false`.

For similar reasons, in `propagate_inequal`, called with  `dom_i=I`, `dom_j=J`, the set of elements that are not satisfied under $J$ should also be not satisfied under $I$ and thus result in all-zero values for `get_weight`.

I feel like I am missing an important point, therefore any clarification on this matter would be greatly appreciated. Thank you in advance!

**Comment by rkaminsk** [comment]
The algorithms are closely aligned with the propositions in the "aggregate propagation" section of the "foundations of grounding" paper. Maybe have a look at propositions 38, 39, 40. The first one shows that we only get implications in general. The second one identifies cases when we get equivalences, and the last one shows which decision problem to solve in the general case. Relating to your case, propagation 39 states that we actually have an equivalence when propagating certain atoms. However, we do not get one when propagating possible atoms (where $J \subseteq I$).

https://arxiv.org/pdf/2108.04769.pdf

**Comment by pdeibert** [comment]
Thank you for your feedback!

I have already read the paper and tried to derive the here implemented algorithm from the propositions, but so far unsuccessfully.

Per definition of `Propagate`, we want to check if $J\vDash\pi_G(a\sigma)_I$ or not.
Then I understand Proposition 39(a) as:
$J\vDash\pi(f\\{E\\} < b)_I\enspace\lor\enspace\pi(f\\{E\\} > b)_I\enspace\Leftrightarrow\enspace J\vDash\pi(f\\{E\\} \ne b)_I$
Is that not the equivalence we are looking for and can use directly?

On the other hand for Proposition 39(b) we only get (due to $I\subseteq J$):
$I\vDash\pi(f\\{E\\} \le b)_J\enspace\lor\enspace\pi(f\\{E\\} \ge b)_J\enspace\Leftrightarrow\enspace I\vDash\pi(f\\{E\\} = b)_J$
This does not seem to be what we are looking for and should not be applicable straight-forwardly (but is according to the code?).

I can only assume that my trouble is the usage of $I$ and $J$ in the propositions (or in the aggregate propagation in general). What does propagating 'certain' or 'possible' atoms mean in formulaic terms and how does it translate to what we would like to compute (i.e., $J\vDash\pi_G(a\theta)_I$)?

**Comment by rkaminsk** [comment]
Ground component, which at some point calls propagate, is invoked in function ground with the roles of I and J interchanged. See the following lines

https://github.com/potassco/mu-gringo/blob/135303a18df30d45dd134c06cbd60c76a4a54f8c/src/grd.rs#L207

https://github.com/potassco/mu-gringo/blob/135303a18df30d45dd134c06cbd60c76a4a54f8c/src/grd.rs#L209

The propagation algorithms are written so that they handle both cases $I \subseteq J$ and $J \subseteq I$.

**Comment by pdeibert** [comment]
This clears up my confusion a bit. Am I correct to assume, then, that some of the cases are not needed depending on the case $I\subseteq J$ or $J\subseteq I$, but are not distinguished to keep the implementation as simple as possible?

Also, why does the case for `#count` and `=` not have any additional check for $I\subseteq J$ where the equality does not hold? Is this due to the strictly increasing nature of `#count`?

**Comment by rkaminsk** [comment]
> This clears up my confusion a bit. Am I correct to assume, then, that some of the cases are not needed depending on the case I⊆J or J⊆I, but are not distinguished to keep the implementation as simple as possible?

Yes, exactly.

> Also, why does the case for `#count` and `=` not have any additional check for I⊆J where the equality does not hold? Is this due to the strictly increasing nature of `#count`?

It's been a while that I wrote the code. I might have forgotten a case here. Note however that this count aggregate is strongly equivalent to the conjunction of two count aggregates with the <= and >= relations. So the grounder still produces correct groundings. Maybe, some simplifications are omitted in this case.

**Comment by pdeibert** [comment]
That answers my original question and I'll close the issue. Thank you for your help!

**Comment by rkaminsk** [comment]
Hi, now that you raised the issue, I was looking a bit closer at the code and noticed that I did not correctly use sets of tuples. This leads to the situation that aggregates elements with overlapping tuples are not handled correctly. For example, the program

```
a :- not b.
b :- not a.
c.
d :- #sum { 1,a: a; 1,a: c } = 1.
e :- not d.
```

does not derive `d` as a fact. This would be relatively easy to fix by extracting the sets of tuples before accumulating in the propagation functions. I think, I'll spend some time to fix these issues.

**Comment by rkaminsk** [comment]
I also removed the `propagate_disjunction` function. For count aggregates, the remaining tests already cover the check in Proposition 40. In fact, we get an "iff" for both $I \subseteq J$ and $J \subseteq I$ in Proposition 39. I think the propositions could be refined further in view of count aggregates.

**Comment by pdeibert** [comment]
Thank you for the info!
