### ISSUE TITLE
Domain K in grounding epsilon & eta rules.

### ISSUE THREAD

**Issue by pdeibert** [potassco/mu-gringo#2]
Algorithm 2 ($\textrm{GroundComponent}$) in the referenced paper calls $\textrm{GroundRule}^{I,J}_{r,f,J'}$ in order to instantiate epsilon and eta rules for aggregates.

In your implementation of `ground_component`, a set $K:=I\cup J$ is used instead, i.e., $\textrm{GroundRule}^{I,I\cup J}_{r,f,J'}$.

My own implementation results in incorrectly ground programs if I adhere to the algorithm in the paper, but seems to ground statements correctly if called with $K=I\cup J$ as it is done in `mu-gringo` (checked using clasp/clingo).

Could you please explain where the set $K$ comes from and how it relates to the algorithm described in the paper?

**Comment by rkaminsk** [comment]
The union is taken to ensure that all elements necessary for aggregate propagation are gathered. To decide whether an aggregate is certain, the propagation also takes into consideration "possible" elements. Unfortunately, I do not remember how this is reflected in the theory/algorithms in the paper. I would have to study this again (Proposition 32 in particular).

Update: There is the possibility that this is a bug in the paper. Theorem 25 requires $I \subseteq J$. The proof of Proposition 32 does not seem to take this into account. In any case, it would be fixable. For example, like in the implementation, by joining with $I$ when grounding the eta/epsilon rules.

**Comment by pdeibert** [comment]
Of course I cannot rule out that there might also be an error in my code, but joining with $I$ seems to fix the issue, as I pointed out, so I will stick with that. Knowing that the issue may also be with the algorithm in the paper at least gives me somewhat more confidence. As a suggestion, a comment in the code could help avoid future readers running into the same confusion. Thank you for your help!

**Comment by rkaminsk** [comment]
I'll update the arxiv paper once I'll find the time. Changes to the main text should be fairly minimal. Only adjusting the proofs is a bit more involved.
